Iter15
artems723/monik pull request #16
Opened 2023-04-03 19:33 UTC by artems723

2023-04-07 20:22 UTC, Barugoo commented on internal/server/httpserver/server.go
> +		WriteTimeout:   31 * time.Second,
Что за магическая цифра 31? Подпиши комментарием откуда она взялась

2023-04-07 20:24 UTC, Barugoo commented on internal/server/storage/memStorage_test.go
> +func BenchmarkMemStorage_GetAllMetrics(b *testing.B) {
В случае с бенчмарками нас часто интересует сравнение производитлеьности двух реализации одного и того же функционала - бенчмарк в вакууме менее ценен
Давай внутри одного бенчмарка соответствующего методу хранилки сравнивать две реализации - с файлом и с мапкой
Можно сделать подбенчмарки через b.Run

2023-04-07 20:27 UTC, Barugoo requested changes
Хорошо, но есть замечание по коду и не вижу примера (Example_ функция в файле _test.go) работы с хэндлером

Можешь вдохновение здесь почерпнуть
https://sourcegraph.com/github.com/golang/go/-/blob/src/net/http/httptest/example_test.go

Здесь ExampleServer()

2023-04-10 13:54 UTC, artems723 commented on internal/server/httpserver/server.go
> +		WriteTimeout:   31 * time.Second,
Готово

2023-04-10 13:54 UTC, artems723 commented on internal/server/storage/memStorage_test.go
> +func BenchmarkMemStorage_GetAllMetrics(b *testing.B) {
Готово

2023-04-12 14:55 UTC, merged