Iter18
artems723/monik pull request #19
Opened 2023-05-16 20:24 UTC by artems723

2023-05-17 21:16 UTC, Barugoo commented on cmd/server/main.go
> +		go grpcsrv.Start()
graceful shutdown для жрпс сервера тоже неплохо было бы добавить

2023-05-17 21:18 UTC, Barugoo commented on internal/server/proto/metrics.proto
> +message SaveListMetricsResponse {}
Используй google.protobuf.Empty:
```go
import "google/protobuf/empty.proto";
//...
rpc Save(SaveMetricRequest) returns(google.protobuf.Empty);

2023-05-17 21:18 UTC, Barugoo commented on internal/server/proto/metrics.proto
> +  repeated Metric metric = 1;
давай назовем в плюральной форме - metric**s**

2023-05-17 21:18 UTC, Barugoo commented on internal/server/proto/metrics.proto
> +  double value = 4;
Давай сделаем эти поля `optional`

2023-05-17 21:18 UTC, Barugoo commented on internal/server/proto/metrics.proto
> +  string mtype = 2;
Давай сделаем тип метрики енумом

2023-05-17 21:18 UTC, Barugoo requested changes
Хорошо, но есть замечания

2023-05-21 07:53 UTC, artems723 commented on cmd/server/main.go
> +		go grpcsrv.Start()
Готово

2023-05-21 07:53 UTC, artems723 commented on internal/server/proto/metrics.proto
> +message SaveListMetricsResponse {}
Готово

2023-05-21 07:54 UTC, artems723 commented on internal/server/proto/metrics.proto
> +  repeated Metric metric = 1;
Готово

2023-05-21 07:54 UTC, artems723 commented on internal/server/proto/metrics.proto
> +  double value = 4;
Готово

2023-05-21 07:54 UTC, artems723 commented on internal/server/proto/metrics.proto
> +  string mtype = 2;
Готово

2023-05-24 07:49 UTC, merged